
export const ALGORITHM_NAMES = {
	BUBBLE_SORT: 'Bubble Sort',
	INSERTION_SORT: 'Insertion Sort',
	SELECTION_SORT: 'Selection sort',
};

export const ALGORITHM_NAMES_ARR = [
	ALGORITHM_NAMES.BUBBLE_SORT,
	ALGORITHM_NAMES.INSERTION_SORT,
	ALGORITHM_NAMES.SELECTION_SORT,
];